### ISSUE TITLE
[Feature request]: Customizable `object-fit` for `sbb-image`

### ISSUE THREAD

**Issue by georgwittberger-telekom-mms** [sbb-design-systems/lyne-components#3133]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

Currently the `sbb-image` component sets the CSS property `object-fit` of the internal `img` elements to the fixed value `cover`.

In some scenarios - e.g. images in `sbb-flip-card` - it is useful to configure a different fitting strategy like `contain` to achieve the desired visual output.

Proposal:

Allow the value of `object-fit` on internal images to be configured externally using the CSS variable `--sbb-image-object-fit`.

```css
:is(.sbb-image__img, .sbb-image__blurred) {
    width: 100%;
    height: 100%;
    object-fit: cover; /* current implementation, replace with following line: */
    object-fit: var(--sbb-image-object-fit, cover);
    object-position: var(--sbb-image-object-position);
    transition: opacity var(--sbb-image-animation-duration) var(--sbb-animation-easing);
}
```
